"""
DOCX Report Generator
"""

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from datetime import datetime
import os

def generate_docx_report(session):
    """Generate DOCX stress report"""
    
    # Create reports directory
    os.makedirs("reports/generated", exist_ok=True)
    
    filename = f"reports/generated/stress_report_{session.session_id}.docx"
    doc = Document()
    
    # Title
    title = doc.add_heading('StressGuardAI - Stress Analysis Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Session Information
    doc.add_heading('Session Information', level=1)
    
    table = doc.add_table(rows=4, cols=2)
    table.style = 'Light Grid Accent 1'
    
    table.cell(0, 0).text = 'Session ID'
    table.cell(0, 1).text = session.session_id
    
    table.cell(1, 0).text = 'Date'
    table.cell(1, 1).text = session.started_at.strftime("%Y-%m-%d %H:%M")
    
    table.cell(2, 0).text = 'Stress Level'
    table.cell(2, 1).text = session.stress_level or "N/A"
    
    table.cell(3, 0).text = 'Average Score'
    table.cell(3, 1).text = f"{session.average_stress_score or 0:.1f}/100"
    
    # Recommendations
    doc.add_heading('AI-Powered Recommendations', level=1)
    
    from backend.utils.recommendation_engine import generate_recommendations
    recommendations = generate_recommendations(session.average_stress_score or 50)
    
    for category, items in recommendations.items():
        doc.add_heading(category.replace('_', ' ').title(), level=2)
        for item in items:
            p = doc.add_paragraph(item, style='List Bullet')
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph('Generated by StressGuardAI')
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save
    doc.save(filename)
    
    return filename
